# Generated by Django 2.0.7 on 2018-09-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecallapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='true_form',
            name='attachment',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
