# Generated by Django 2.0.7 on 2018-09-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truecallapp', '0003_auto_20180902_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='true_form',
            old_name='Attachment',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='true_form',
            old_name='Cover_Later',
            new_name='cover_Later',
        ),
        migrations.RenameField(
            model_name='true_form',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='true_form',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='true_form',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='true_form',
            old_name='Platform',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='true_form',
            old_name='Region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='true_form',
            old_name='Subject',
            new_name='subject',
        ),
    ]
