# Generated by Django 2.0.7 on 2018-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecallapp', '0004_auto_20180902_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='careerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.IntegerField()),
                ('Linkedin_Profile', models.URLField(blank=True)),
                ('Website', models.URLField(blank=True)),
                ('How_did_you_know_about_this_job', models.CharField(max_length=100)),
                ('Attachment', models.FileField(blank=True, upload_to='files')),
                ('Cover_Later', models.ImageField(blank=True, upload_to='cover_Later')),
            ],
        ),
        migrations.RemoveField(
            model_name='true_form',
            name='cover_Later',
        ),
    ]
